### ISSUE TITLE
Removal of num_updates in applying crm diff to cibadmin for configuration updates

### ISSUE THREAD

**Issue by seabres** [crmsh/crmsh#63]
The cib versioning uses epoch configuration and num_updates for status changes.
In an heavy used big system with lot of attribute changes and updates apply of configuration often fail with cib error "update was older than existing configuration".

Reason is the fact, that every status update increments num_updates and it is a high chance that source num_updates has changed when offending the xml diff to cibadmin.

A possible fix for this scenario is to remove num_updates from the offending cib diff.
As we rely on epoch for configuration updates, it does not brake the cib version check.

With Pacemaker 1.1.12 this is verified to work.
If num_updates is not present, neither for source nor target, cibadmin applies the xml diff for every current num_updates and set the new one to 0.

Example:
cib counters when cib_origin was taken epoch="562" num_updates="237"
cib has changed in the meanwhile due to status updates epoch="562" num_updates="275"
XML diff which crmsh wants to apply:
< version >
    < source admin_epoch="0" epoch="562" num_updates="237"/>
    < target admin_epoch="0" epoch="563" num_updates="237"/>
< /version>
This fails due to num_updates.
Possible changed XML diff to apply:
< version>
    < source admin_epoch="0" epoch="562"/>
    < target admin_epoch="0" epoch="563"/>
< /version>
This diff gets applied and cib start with epoch="563" and num_updates="0".

**Comment by krig** [comment]
This should be fixed by #75
